### ISSUE TITLE
Nav Drawer Buttons Activation Delay

### ISSUE THREAD

**Issue by stonecoder19** [UWICompSociety/FSTApp#8]
There is a huge delay after you have logged in to wait on the view timetable button and view transcript buttons to appear.Probably you should try getting all that data during login before going to the nav bar or have a tiny progress bar beside the button to indicate to the user that something is happening

**Comment by macsual** [comment]
If there's going to be a disabled button shown anyway, I also think that the button should only appear disabled and upon tapping it, a Toast could be shown to the user with an informative message explaining why the button appears to be disabled.

**Comment by sultanofcardio** [comment]
Good suggestion. Both ideas can be combined
